language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - openssl aes-256-cbc -K $encrypted_e51a7a963465_key -iv $encrypted_e51a7a963465_iv
    -in id_rsa.enc -out id_rsa -d
script:
  - yarn lint
  - yarn test
after_success:
  - yarn build
deploy:
  provider: script
  script: tools/deploy.sh
